# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: nitin_couponmandi
  pool: 5
  timeout: 5000
  username: root
  password: vi156vi

test:
  adapter: mysql2
  database: nitin_couponmandi
  pool: 5
  timeout: 5000
  username: root
  password: vi156vi

production:
  adapter: mysql2
  database: nitin_couponmandi
  pool: 5
  timeout: 5000
  username: root
  password: vi156vi
